

server:
  port: 8080
  servlet:
    context-path: /diancan
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diancan?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
